{% set name = "citeproc" %}
{% set version = "1.0.10" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 829a0a2e291a3afd1cde39dce4880df6253b0fecd26226275265ea59a52e748f

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-namae >=1.0,<2

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: BSD-2-Clause
  license_family: BSD
  license_file: {{ name }}-{{ version }}/BSDL
  summary: A cite processor interface for Citation Style Language (CSL) styles.

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/inukshuk/{{ name }}

extra:
  recipe-maintainers:
    - sodre
