travis:
  secure:
    BINSTAR_TOKEN: uIz8UN+UxaSc6us4imxshdqihepFLoT3e3ruVt7VnHmWLSqe4IUgePhFWu/cFD2e8UXH1hq1F3klJSUVe22I6rigZ45BCDSwAZ2heoXdXULug4Z1ErEib/LYt28hM3eFgsurfZJCfZQNF9NPnzB3HeU67DoPWhF99ynHKG06m763p3yGaI3FDqrCH/QL+O233g3cmbb/2lUh69SJyw1P2FcIWOqjQBLwOGmfD6UEN34+g0Nns+bHVigNGgRI05LzNl0gvIxFCSfLfuiVoLDx0DQYaMj02puc1030rtSFbDRnrRRKNhOoAAn725fMIgmwT3WxWWJkM8u/Giz707VHpkowLZncbsdHHxV0ARqUyTgwHyzEFacXefsanrcm1KVNCRj0iZdZpV+CI+5O7IfcDGqc+/xBCjoawzwOlpFbHA3xH9W7kPaoPMJdHvYaB4OYSxj3wkotBQgO5s4vpAUEWtMaZwfwAXH4bMBmvwU+jTI9oukl3WIM6V6tae1dS4s/YH+LGyXcl74r2PEcT4j6qD4u6yvKin1MYgA3xvAXwK4ZsyAf+sn7PwoLXVt5m34X9uDtl/H/Azh8helV6oQNMpippF1U2B2OHrGBFPLefiPRvk3J9TLeydVKPO4QsiyAl1riAAMgVptMbim9yuv3xOJOcxDGbywQWd3xrd/2RUo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
